local colors = require("konoha.colors")

local M = {}

M.setup = function()
  local theme = {
    colors = colors,
  }

  local c = theme.colors

  theme.highlights = {
    Comment = { fg = c.comment, ctermfg = c.comment_256 },
    Cursor = { fg = c.bg, bg = c.white, ctermfg = c.bg_highlight_256, ctermbg = c.white_256 },
    lCursor = { fg = c.bg, bg = c.white, ctermfg = c.bg_highlight_256, ctermbg = c.white_256 },
    CursorColumn = { bg = c.bg_highlight, ctermbg = c.bg_highlight_256 },
    CursorLine = { bg = c.bg_highlight, ctermbg = c.bg_highlight_256 },
    Directory = { fg = c.blue1, ctermfg = c.blue1_256, bold = true },
    DiffAdd = { bg = c.blue1, ctermbg = c.blue1_256 },
    DiffChange = { bg = c.brown1, ctermbg = c.brown1_256 },
    DiffDelete = { bg = c.red3, ctermbg = c.red3_256 },
    DiffText = { bg = c.bg_highlight, ctermbg = c.bg_highlight_256 },
    EndOfBuffer = { fg = c.bg_gutter, ctermfg = c.bg_gutter_256 },
    ErrorMsg = { fg = c.yellow1, bg = c.red1, ctermfg = c.yellow1_256, ctermbg = c.red1_256 },
    FoldColumn = { fg = c.green2, bg = c.bg_highlight, ctermfg = c.green2_256, ctermbg = c.bg_highlight_256 },
    Folded = { fg = c.comment, bg = c.bg_gutter, ctermfg = c.comment_256, ctermbg = c.bg_gutter_256 },
    SignColumn = { bg = c.bg_gutter, ctermbg = c.bg_gutter_256 },
    Substitute = { fg = c.green2, bg = c.bg_gutter, ctermfg = c.green2_256, ctermbg = c.bg_gutter_256 },
    LineNr = { fg = c.fg_gutter, bg = c.bg_gutter, ctermfg = c.fg_gutter_256, ctermbg = c.bg_gutter_256 },
    CursorLineNr = { fg = c.orange2, ctermfg = c.orange2_256, underline = true },
    MatchParen = { fg = c.orange2, ctermfg = c.orange2_256, bold = true },
    NonText = {  fg = c.bg_gutter, ctermfg = c.bg_gutter_256 },
    ModeMsg = { fg = c.fg_gutter, ctermfg = c.fg_gutter_256 },
--    MsgArea = { fg = c.fg_dark },
    Normal = { fg = c.white, ctermfg = c.white_256 },
    NormalNC = { fg = c.gray1, ctermfg = c.gray1_256 },
    NormalSB = { fg = c.yellow1, ctermfg = c.yellow1_256 },
    NormalFloat = { fg = c.gray1, bg = c.bg_gutter, ctermfg = c.gray1_256, ctermbg = c.bg_gutter_256 },
    Pmenu = { fg = c.bg_highlight, bg = c.yellow1, ctermfg = c.bg_highlight_256, ctermbg = c.yellow1_256 },
    PmenuSel = { fg = c.bg_highlight, bg = c.fg_status, ctermfg = c.bg_highlight_256, ctermbg = c.fg_status_256, bold = true },
    PmenuSbar = { fg = c.bg_highlight, ctermfg = c.bg_highlight_256 },
    PmenuThumb = { bg = c.fg_status, ctermbg = c.fg_status_256 },
    Question = { fg = c.yellow1, ctermfg = c.yellow1_256 },
    SpecialKey = { fg = c.green2, ctermfg = c.green2_256 },
    Search = { fg = c.yellow1, bg = c.green3, ctermfg = c.yellow1_256, ctermbg = c.green3_256 },
    IncSearch = { fg = c.yellow1, bg = c.orange5, ctermfg = c.yellow1_256, ctermbg = c.orange5_256 },
    SpellBad = { sp = c.red1, undercurl = true },
    SpellCap = { sp = c.orange1, undercurl = true },
    SpellLocal = { sp = c.yellow1, undercurl = true },
    SpellRare = { sp = c.blue1, undercurl = true },
    StatusLine = { fg = c.kaki1, bg = c.bg_gutter, ctermfg = c.kaki1_256, ctermbg = c.bg_gutter_256 },
    StatusLineNC = { fg = c.comment, bg = c.bg_gutter, ctermfg = c.comment_256, ctermbg = c.bg_gutter_256 },
    TabLine = { fg = c.comment, bg = c.bg_gutter, ctermfg = c.comment_256, ctermbg = c.bg_gutter_256 },
    TabLineFill = { fg = c.bg_gutter, ctermfg = c.bg_gutter_256 },
    TabLineSel = { fg = c.kaki1, bg = c.bg_highlight, ctermfg = c.kaki1_256, ctermbg = c.bg_highlight_256 },
    Title = { fg = c.cyan1, ctermfg = c.cyan1_256 },
    VertSplit = { fg = c.bg_gutter, bg = c.bg_highlight, ctermfg = c.bg_gutter_256, ctermbg = c.bg_highlight_256 },
    Visual = { bg = c.fg_status, fg = c.yellow1, ctermfg = c.yellow1_256 },
    VisualNOS = { bg = c.green3, fg = c.yellow1, ctermbg = c.green3_256, ctermfg = c.yellow1_256 },
    Constant = { fg = c.red1, ctermfg = c.red1_256 },
    String = { fg = c.orange1, ctermfg = c.orange1_256 },
    Character = { fg = c.red1, ctermfg = c.red1_256 },
    Number = { fg = c.red2, ctermfg = c.red2_256 },
    Boolean = { fg = c.red1, ctermfg = c.red1_256 },
    Error = { fg = c.red1, bg = c.red3, ctermfg = c.red1_256, ctermbg = c.red3_256 },
    Identifier = { fg = c.green1, ctermfg = c.green1_256 },
    Function = { fg = c.green2, ctermfg = c.green2_256 },
    Statement = { fg = c.comment, ctermfg = c.yellow1_256 },
    Conditional = { fg = c.orange1, ctermfg = c.orange1_256 },
    Repeat = { fg = c.fg_gutter, ctermfg = c.fg_gutter_256 },
    Label = { fg = c.red2, ctermfg = c.red2_256 },
    Keyword = { fg = c.yellow1, ctermfg = c.yellow1_256 },
    PreProc = { fg = c.red2, ctermfg = c.red2_256, bold = true },
    Include = { fg = c.red2, ctermfg = c.red2_256 },
    Define = { fg = c.red2, ctermfg = c.red2_256, bold = true },
    PreCondit = { fg = c.red3, ctermfg = c.red3_256, bold = true },
    Type = { fg = c.kaki1, ctermfg = c.kaki1_256 },
    Structure = { fg = c.kaki1, ctermfg = c.kaki1_256 },
    Special = { fg = c.cyan1, ctermfg = c.cyan1_256 },
    SpecialChar = { fg = c.purple1, ctermfg = c.purple1_256 },
    Delimiter = { fg = c.green2, ctermfg = c.green2_256 },
    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Todo = { fg = c.yellow1, bg = c.bg_highlight, ctermfg = c.yellow1_256, ctermbg = c.bg_highlight_256, bold = true },
  }
  return theme
end

return M
