local colors = require("konoha.colors")

local M = {}

M.setup = function()
  local theme = {
    colors = colors,
  }

  local c = theme.colors

  theme.highlights = {
    Comment = { fg = c.comment },
    Cursor = { fg = c.bg, bg = c.fg },
    lCursor = { fg = c.bg, bg = c.fg },
    CursorColumn = { bg = c.bg_highlight },
    CursorLine = { bg = c.bg_highlight },
    Directory = { fg = c.blue1, bold = true },
    DiffAdd = { bg = c.blue1 },
    DiffChange = { bg = c.brown1 },
    DiffDelete = { bg = c.red7 },
    DiffText = { bg = c.bg_highlight },
    EndOfBuffer = { fg = bg_gutter },
    ErrorMsg = { fg = c.orange2, bg = c.red2 },
    FoldColumn = { fg = c.green2, bg = c.bg },
    Folded = { fg = c.comment, bg = c.bg_gutter },
    SignColumn = { bg = c.bg_gutter },
    Substitute = { fg = c.green3, bg = c.gray2 },
    LineNr = { fg = c.fg_gutter, bg = c.bg_gutter },
    CursorLineNr = { fg = c.orange5, underline = true },
    MatchParen = { fg = c.orange4, bold = true },
    NonText = {  fg = c.gray2 },
    ModeMsg = { fg = c.fg_gutter },
--    MsgArea = { fg = c.fg_dark },
    Normal = { fg = c.white },
    NormalNC = { fg = c.gray4 },
    NormalSB = { fg = c.yellow2 },
    NormalFloat = { fg = c.gray4, bg = c.bg_gutter },
    Pmenu = { fg = c.bg_highlight, bg = c.yellow2 },
    PmenuSel = { fg = c.green3, bg = c.bg_highlight, bold = true },
    PmenuSbar = { fg = c.bg_highlight },
    PmenuThumb = { fg = c.gray3 },
    Question = { fg = c.yellow1 },
    SpecialKey = { fg = c.kaki3 },
    Search = { fg = c.yellow3, bg = c.green6 },
    IncSearch = { fg = c.yellow3, bg = c.orange5 },
    SpellBad = { sp = c.red2, undercurl = true },
    SpellCap = { sp = c.orange4, undercurl = true },
    SpellLocal = { sp = c.yellow2, undercurl = true },
    SpellRare = { sp = c.blue1, undercurl = true },
    StatusLine = { fg = c.kaki1, bg = c.bg_gutter },
    StatusLineNC = { fg = c.comment, bg = c.bg_gutter },
    TabLine = { fg = c.comment, bg = c.bg_gutter },
    TabLineFill = { fg = c.bg_gutter },
    TabLineSel = { fg = c.kaki1, bg = c.bg_gutter },
    Title = { fg = c.cyan2 },
    VertSplit = { fg = c.bg, bg = c.bg_highlight },
    Visual = { bg = c.green2, fg = c.yellow1 },
    VisualNOS = { bg = c.green4, bg = c.kaki2 },
    Constant = { fg = c.red1 },
    String = { fg = c.orange1 },
    Character = { fg = c.red2 },
    Number = { fg = c.cyan1 },
    Boolean = { fg = c.red3 },
    Error = { fg = c.red2, bg = c.red6 },
    Identifier = { fg = c.green1 },
    Function = { fg = c.green2 },
    Statement = { fg = c.comment },
    Conditional = { fg = c.orange2 },
    Repeat = { fg = c.fg_gutter },
    Label = { fg = c.red4 },
    Keyword = { fg = c.yellow2 },
    PreProc = { fg = c.red4, bold = true },
    Include = { fg = c.red5 },
    Define = { fg = c.red1, bold = true },
    PreCondit = { fg = c.red6, bold = true },
    Type = { fg = c.kaki1 },
    Structure = { fg = c.kaki1 },
    Special = { fg = c.purple2 },
    SpecialChar = { fg = c.purple1 },
    Delimiter = { fg = c.green5 },
    Underlined = { underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Todo = { fg = c.yellow1, bg = c.bg_highlight, bold = true },
  }
  return theme
end

return M
